package org.apidb.apicommon.model.comment.repo;

public interface Table {
  String COMMENT_TO_EXT_DB    = "COMMENT_EXTERNAL_DATABASE";
  String COMMENT_TO_REFERENCE = "COMMENTREFERENCE";
  String COMMENT_TO_STABLE_ID = "COMMENTSTABLEID";
  String COMMENT_TO_SEQUENCE  = "COMMENTSEQUENCE";
  String COMMENT_TO_CATEGORY  = "COMMENTTARGETCATEGORY";
  String COMMENT_TO_LOCATION  = "LOCATION";

  String COMMENT_USERS = "COMMENT_USERS";
  String COMMENTS      = "COMMENTS";
  String EXTERNAL_DB   = "EXTERNAL_DATABASE";
}
