
package GUS::Model::DoTS::AssemblySequenceSNP;

# THIS CLASS HAS BEEN AUTOMATICALLY GENERATED BY THE GUS::ObjRelP::Generator 
# PACKAGE.
#
# DO NOT EDIT!!

# TO ADD FUNCTIONALITY MANUALLY, COPY THIS FILE TO AssemblySequenceSNP.pm.man
# (or edit that file if it already exists) AND ADD THE FUNCTIONALITY THERE.
# THEN RE-GENERATE THE GUS OBJECTS.

use strict;
use GUS::Model::DoTS::AssemblySequenceSNP_Row;



use vars qw (@ISA);
@ISA = qw (GUS::Model::DoTS::AssemblySequenceSNP_Row);


1;

