package GUS::Model::DoTS::AssemblySequenceSNP_Table;

# THIS CLASS HAS BEEN AUTOMATICALLY GENERATED BY THE GUS::ObjRelP::Generator 
# PACKAGE.
#
# DO NOT EDIT!!


use strict;
use GUS::ObjRelP::DbiTable;
use vars qw (@ISA);
@ISA = qw (GUS::ObjRelP::DbiTable);

sub setDefaultParams {
  my $self = shift;
  $self->setChildList();

  $self->setParentList(
      ['GUS::Model::DoTS::AssemblySequence','assembly_sequence_id','assembly_sequence_id'],
      ['GUS::Model::DoTS::AssemblySNP','assembly_snp_id','assembly_snp_id'],
      ['GUS::Model::Core::AlgorithmInvocation','row_alg_invocation_id','algorithm_invocation_id'],
      ['GUS::Model::Core::GroupInfo','row_group_id','group_id'],
      ['GUS::Model::Core::UserInfo','row_user_id','user_id'],
      ['GUS::Model::Core::ProjectInfo','row_project_id','project_id']);

  $self->setAttributeNames(
      'assembly_sequence_snp_id',
      'assembly_sequence_id',
      'assembly_snp_id',
      'gapped_location',
      'na_sequence_location',
      'sequence_character',
      'modification_date',
      'user_read',
      'user_write',
      'group_read',
      'group_write',
      'other_read',
      'other_write',
      'row_user_id',
      'row_group_id',
      'row_project_id',
      'row_alg_invocation_id');

  $self->setQuotedAtts(
      'modification_date',
      'sequence_character');

  $self->setAttInfo(
      {'col' => 'assembly_sequence_snp_id', 'type' => 'NUMBER', 'prec' => 10, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'assembly_sequence_id', 'type' => 'NUMBER', 'prec' => 10, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'assembly_snp_id', 'type' => 'NUMBER', 'prec' => 10, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'gapped_location', 'type' => 'NUMBER', 'prec' => 8, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'na_sequence_location', 'type' => 'NUMBER', 'prec' => 8, 'length' => 22, 'Nulls' => 1, 'base_type' => 'not set'}, 
      {'col' => 'sequence_character', 'type' => 'CHAR', 'prec' => '', 'length' => 1, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'modification_date', 'type' => 'DATE', 'prec' => '', 'length' => 7, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'user_read', 'type' => 'NUMBER', 'prec' => 1, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'user_write', 'type' => 'NUMBER', 'prec' => 1, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'group_read', 'type' => 'NUMBER', 'prec' => 1, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'group_write', 'type' => 'NUMBER', 'prec' => 1, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'other_read', 'type' => 'NUMBER', 'prec' => 1, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'other_write', 'type' => 'NUMBER', 'prec' => 1, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'row_user_id', 'type' => 'NUMBER', 'prec' => 12, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'row_group_id', 'type' => 'NUMBER', 'prec' => 4, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'row_project_id', 'type' => 'NUMBER', 'prec' => 4, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'row_alg_invocation_id', 'type' => 'NUMBER', 'prec' => 12, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'});

  $self->setRealTableName('GUS::Model::DoTS::AssemblySequenceSNP');

  $self->setIsView(0);

  $self->setParentRelations(
      ['GUS::Model::DoTS::AssemblySequence','assembly_sequence_id','assembly_sequence_id'], 
      ['GUS::Model::DoTS::AssemblySNP','assembly_snp_id','assembly_snp_id'], 
      ['GUS::Model::Core::AlgorithmInvocation','row_alg_invocation_id','algorithm_invocation_id'], 
      ['GUS::Model::Core::GroupInfo','row_group_id','group_id'], 
      ['GUS::Model::Core::UserInfo','row_user_id','user_id'], 
      ['GUS::Model::Core::ProjectInfo','row_project_id','project_id']);

  $self->setChildRelations();

  $self->setHasSequence(0);

  $self->setPrimaryKeyList('assembly_sequence_snp_id');

  $self->setTableId(480);

}

1;

