package GUS::Model::DoTS::TranslatedAASequence_Row;

# THIS CLASS HAS BEEN AUTOMATICALLY GENERATED BY THE GUS::ObjRelP::Generator 
# PACKAGE.
#
# DO NOT EDIT!!

use strict;
use GUS::Model::DoTS::AASequence;

use vars qw (@ISA);
@ISA = qw (GUS::Model::DoTS::AASequence);

sub setDefaultParams {
  my ($self) = @_;
  $self->setVersionable(1);
  $self->setUpdateable(1);
}

sub setNotes {
  my($self,$value) = @_;
  $self->set("notes",$value);
}

sub getNotes {
    my($self) = @_;
  return $self->get("notes");
}

sub setIsSimple {
  my($self,$value) = @_;
  $self->set("is_simple",$value);
}

sub getIsSimple {
    my($self) = @_;
  return $self->get("is_simple");
}

sub setSecondaryIdentifier {
  my($self,$value) = @_;
  $self->set("secondary_identifier",$value);
}

sub getSecondaryIdentifier {
    my($self) = @_;
  return $self->get("secondary_identifier");
}

1;
