package GUS::Model::DoTS::VirtualSequence_Row;

# THIS CLASS HAS BEEN AUTOMATICALLY GENERATED BY THE GUS::ObjRelP::Generator 
# PACKAGE.
#
# DO NOT EDIT!!

use strict;
use GUS::Model::DoTS::NASequence;

use vars qw (@ISA);
@ISA = qw (GUS::Model::DoTS::NASequence);

sub setDefaultParams {
  my ($self) = @_;
  $self->setVersionable(1);
  $self->setUpdateable(1);
}

sub setConfidence {
  my($self,$value) = @_;
  $self->set("confidence",$value);
}

sub getConfidence {
    my($self) = @_;
  return $self->get("confidence");
}

sub setSourceId {
  my($self,$value) = @_;
  $self->set("source_id",$value);
}

sub getSourceId {
    my($self) = @_;
  return $self->get("source_id");
}

sub setSecondaryIdentifier {
  my($self,$value) = @_;
  $self->set("secondary_identifier",$value);
}

sub getSecondaryIdentifier {
    my($self) = @_;
  return $self->get("secondary_identifier");
}

sub setChromosome {
  my($self,$value) = @_;
  $self->set("chromosome",$value);
}

sub getChromosome {
    my($self) = @_;
  return $self->get("chromosome");
}

sub setChromosomeOrderNum {
  my($self,$value) = @_;
  $self->set("chromosome_order_num",$value);
}

sub getChromosomeOrderNum {
    my($self) = @_;
  return $self->get("chromosome_order_num");
}

1;
