#!/usr/bin/perl

use strict;

use lib "@targetDir@/lib/perl";
$ENV{GUS_HOME} = '@targetDir@';

use ApiCommonWebsite::View::CgiApp::MultipleAlignmentMercatorMavid;

my $app =
  ApiCommonWebsite::View::CgiApp::MultipleAlignmentMercatorMavid->new();

$app->go();
