#!/usr/bin/perl -w

use strict;

use lib "@targetDir@/lib/perl";
$ENV{GUS_HOME} = '@targetDir@';

use ApiCommonWebsite::View::CgiApp::Api_SequenceRetrievalToolContigs;

my $app =
  ApiCommonWebsite::View::CgiApp::Api_SequenceRetrievalToolContigs->new();

$app->go();



