#!/usr/bin/perl 

use strict;

use lib "@targetDir@/lib/perl";
$ENV{GUS_HOME} = '@targetDir@';

use ApiCommonWebsite::View::CgiApp::SequenceRetrievalToolGeneOrf;

my $app =
  ApiCommonWebsite::View::CgiApp::SequenceRetrievalToolGeneOrf->new();

$app->{geneOrOrf} = 'ORF';
$app->{isApiDB} = 1;

$app->go();



