#!/usr/bin/perl -w

use strict;

use lib "@targetDir@/lib/perl";
$ENV{GUS_HOME} = '@targetDir@';

use ApiDBWebsite::View::CgiApp::Api_SequenceRetrievalToolContigs;

my $app =
  ApiDBWebsite::View::CgiApp::Api_SequenceRetrievalToolContigs->new();

$app->go();



