#!/usr/bin/perl -w

use strict;

use lib "@targetDir@/lib/perl";
$ENV{GUS_HOME} = '@targetDir@';

use ApiCommonWebsite::View::CgiApp::SequenceRetrievalToolContigs;

my $app =
  ApiCommonWebsite::View::CgiApp::SequenceRetrievalToolContigs->new();

$app->{type} = 'contig';

$app->go();



