#!/usr/bin/perl 

use strict;

use lib "@targetDir@/lib/perl";
$ENV{GUS_HOME} = '@targetDir@';

use ApiCommonWebsite::View::CgiApp::GeneImage;

my $app = ApiCommonWebsite::View::CgiApp::GeneImage->new();

$app->go(); 
