#!/usr/bin/perl 

use strict;

use lib "@targetDir@/lib/perl";
$ENV{GUS_HOME} = '@targetDir@';

use ApiCommonWebsite::View::CgiApp::SequenceRetrievalToolGenes;

my $app =
  ApiCommonWebsite::View::CgiApp::SequenceRetrievalToolGenes->new(ConfigFile => "$ENV{GUS_HOME}/config/gus.config");

$app->go();



