#!/usr/bin/perl -w

# balloon popups - reads gbrowse feature files 

use strict;
use warnings;
use lib $ENV{GUS_HOME};
use CGI qw(param header);

my $f = param('f');  # feature full name e.g. gene:annotation(PF11_0240)
my $t = param('t');  # feature type e.g. gene:annotation
my $n = param('n');  # feature name e.g. PF11_0240

#return unless $f;

my $root = $ENV{DOCUMENT_ROOT};
open(F, "$root/gbrowse/tmp/$f") if $f;
open(F, "$root/gbrowse/tmp/$t/$n") if ($t && $n);

exit unless ($f || ($t && $n));

my $html = "<table border=0>";

while(<F>) {
  my ($h, $c) = split /\t/, $_;
	$html.= "<tr><td>$h</td><td>$c</td></tr>";
}
$html .= "</table>";
# $html .= '<script language="text/javascript"> alert("Yay!"); </script>';

close F;
print header;
print $html;
