#!/usr/bin/perl 

use strict;

use lib "@targetDir@/lib/perl";
$ENV{GUS_HOME} = '@targetDir@';

use CGI qw/:standard/;
use ApiCommonWebsite::View::CgiApp::IsolateClustalw;
use ApiCommonWebsite::View::CgiApp::HtsSNPAlignment;

my $app;
my $cgi = new CGI;

my $type  = $cgi->param('type');

if($type =~ /htsSNP/i || $type =~ /fasta/i) {
  $app = ApiCommonWebsite::View::CgiApp::HtsSNPAlignment->
    new(ConfigFile => "cryptoModel");
} else {
  $app = ApiCommonWebsite::View::CgiApp::IsolateClustalw->
    new(ConfigFile => "cryptoModel");
}

$app->go();
