#!/usr/bin/perl 

use strict;

use lib "@targetDir@/lib/perl";
$ENV{GUS_HOME} = '@targetDir@';

use ApiCommonWebsite::View::CgiApp::SequenceRetrievalToolOrfs;

my $app =
  ApiCommonWebsite::View::CgiApp::SequenceRetrievalToolOrfs->new();

$app->go();



