#!/usr/bin/perl

use lib "$ENV{GUS_HOME}/lib/perl";

use ApiCommonShared::Model::pcbiPubmed;
use ApiCommonShared::Model::XMLUtils;
use CGI; 
use strict;

my $q = new CGI;

print $q->header('text/html');
my $idstr = $q->param('pmids');

my @ids = split /[-|,]/, $idstr;

foreach my $id (@ids) {

  next if($id.length == 0);
	my $content = ApiCommonShared::Model::pcbiPubmed::setPubmedID($id);

	my $title   = ApiCommonShared::Model::pcbiPubmed::fetchTitle($content, "ArticleTitle");
	my $journal = ApiCommonShared::Model::pcbiPubmed::fetchPublication($content, "Journal");
	my $author  = ApiCommonShared::Model::pcbiPubmed::fetchAuthorList($content, "Author");
	my $url     = ApiCommonShared::Model::pcbiPubmed::fetchPubmedUrl();

print <<EOL
<table class=mybox>
<tr bgcolor="lightgrey">
  <td width=5>PMID:</td>
  <td><a href="$url">$id</a></td>
</tr>
<tr>
  <td>Title:</td>
  <td>$title</td>
</tr>
<tr>
  <td>Journal:</td>
  <td>$journal</td>
</tr>
<tr>
  <td>Author:</td>
  <td>$author</td>
</tr>
<tr>
  <td colspan=2><hr></td>
</tr>
</table>
EOL

}
