#!/usr/bin/perl -T

# Test module for CgiApp and mod-perl
# returns SYSDATE from dual and reports if 
# running in  cgi or Apache::Registry environment

use strict;
use lib "/var/www/CryptoDB/cryptodb.msh/gus_home/lib/perl";
use ApiCommonWebsite::View::CgiApp::SimpleDbQuery;

my $app =
  ApiCommonWebsite::View::CgiApp::SimpleDbQuery->new();

$app->go();



