#!/usr/bin/perl

# Simple cgi script for testing cgi or mod-perl Apache::Registry configurations
# and ApiCommonWebsite::Model::ModelConfig. 
# Returns SYSDATE from dual.
# Requires WDK model-config file for DBI connection strings.

use strict;
use lib $ENV{GUS_HOME};
use DBI;
use CGI qw/:standard/;
use CGI::Carp qw(fatalsToBrowser set_message);
use ApiCommonWebsite::Model::ModelConfig;

BEGIN {

    # Carp callback for sending fatal messages to browser
    sub handle_errors {
        my ($msg) = @_;
        print "<h3>Oops</h3>";
        print "<p>Got an error: <pre>$msg</pre>";
    }
    set_message(\&handle_errors);
}

my $q = new CGI;

my $model = $q->param('model') or die <<"EOF";
WDK model file not specified. Try one of the following:
@{[$q->url]}?model=apiModel
@{[$q->url]}?model=cryptoModel
@{[$q->url]}?model=plasmoDbModel
@{[$q->url]}?model=toxoDbModel
EOF

my $c = new ApiCommonWebsite::Model::ModelConfig($model);


my $dbh = DBI->connect(
    $c->{dbiDsn},
    $c->{login},
    $c->{password},
    { PrintError => 1,
      RaiseError => 0
    }
) or die "Can't connect to the database: $DBI::errstr\n";;

my $sql = q(select sysdate from dual);

my $sth = $dbh->prepare($sql);
$sth->execute();

print $q->header();

print "DSN: ", $c->{dbiDsn}, "<p>";

while (my @row = $sth->fetchrow_array) {
    print $row[0] . "<br>\n";
}

$sth->finish();

