#!/usr/bin/perl

# CGI script prints current time. Does not require
# a database connection. For testing general CGI environments.

use strict;
use lib $ENV{GUS_HOME};
use CGI qw/:standard/;
use CGI::Carp qw(fatalsToBrowser set_message);


BEGIN {

    # Carp callback for sending fatal messages to browser
    sub handle_errors {
        my ($msg) = @_;
        print "<h3>Oops</h3>";
        print "<p>Got an error: <pre>$msg</pre>";
    }
    set_message(\&handle_errors);
}

my $q = new CGI;

print $q->header();

my $now = localtime;

print $now . "\n";