package GUS::Model::DoTS::NASequence_Row;

# THIS CLASS HAS BEEN AUTOMATICALLY GENERATED BY THE GUS::ObjRelP::Generator 
# PACKAGE.
#
# DO NOT EDIT!!

use strict;
use GUS::Model::GusRow;

use vars qw (@ISA);
@ISA = qw (GUS::Model::GusRow);

sub setDefaultParams {
  my ($self) = @_;
  $self->setVersionable(1);
  $self->setUpdateable(1);
}

sub setNaSequenceId {
  my($self,$value) = @_;
  $self->set("na_sequence_id",$value);
}

sub getNaSequenceId {
    my($self) = @_;
  return $self->get("na_sequence_id");
}

sub setSequenceVersion {
  my($self,$value) = @_;
  $self->set("sequence_version",$value);
}

sub getSequenceVersion {
    my($self) = @_;
  return $self->get("sequence_version");
}

sub setSubclassView {
  my($self,$value) = @_;
  $self->set("subclass_view",$value);
}

sub getSubclassView {
    my($self) = @_;
  return $self->get("subclass_view");
}

sub setSequenceTypeId {
  my($self,$value) = @_;
  $self->set("sequence_type_id",$value);
}

sub getSequenceTypeId {
    my($self) = @_;
  return $self->get("sequence_type_id");
}

sub setSequenceOntologyId {
  my($self,$value) = @_;
  $self->set("sequence_ontology_id",$value);
}

sub getSequenceOntologyId {
    my($self) = @_;
  return $self->get("sequence_ontology_id");
}

sub setTaxonId {
  my($self,$value) = @_;
  $self->set("taxon_id",$value);
}

sub getTaxonId {
    my($self) = @_;
  return $self->get("taxon_id");
}

sub setSequence {
  my($self,$value) = @_;
  $self->set("sequence",$value);
}

sub getSequence {
    my($self) = @_;
  return $self->get("sequence");
}

sub setLength {
  my($self,$value) = @_;
  $self->set("length",$value);
}

sub getLength {
    my($self) = @_;
  return $self->get("length");
}

sub setACount {
  my($self,$value) = @_;
  $self->set("a_count",$value);
}

sub getACount {
    my($self) = @_;
  return $self->get("a_count");
}

sub setCCount {
  my($self,$value) = @_;
  $self->set("c_count",$value);
}

sub getCCount {
    my($self) = @_;
  return $self->get("c_count");
}

sub setGCount {
  my($self,$value) = @_;
  $self->set("g_count",$value);
}

sub getGCount {
    my($self) = @_;
  return $self->get("g_count");
}

sub setTCount {
  my($self,$value) = @_;
  $self->set("t_count",$value);
}

sub getTCount {
    my($self) = @_;
  return $self->get("t_count");
}

sub setOtherCount {
  my($self,$value) = @_;
  $self->set("other_count",$value);
}

sub getOtherCount {
    my($self) = @_;
  return $self->get("other_count");
}

sub setDescription {
  my($self,$value) = @_;
  $self->set("description",$value);
}

sub getDescription {
    my($self) = @_;
  return $self->get("description");
}

sub setExternalDatabaseReleaseId {
  my($self,$value) = @_;
  $self->set("external_database_release_id",$value);
}

sub getExternalDatabaseReleaseId {
    my($self) = @_;
  return $self->get("external_database_release_id");
}

sub setSourceNaSequenceId {
  my($self,$value) = @_;
  $self->set("source_na_sequence_id",$value);
}

sub getSourceNaSequenceId {
    my($self) = @_;
  return $self->get("source_na_sequence_id");
}

sub setSequencePieceId {
  my($self,$value) = @_;
  $self->set("sequence_piece_id",$value);
}

sub getSequencePieceId {
    my($self) = @_;
  return $self->get("sequence_piece_id");
}

sub setSequencingCenterContactId {
  my($self,$value) = @_;
  $self->set("sequencing_center_contact_id",$value);
}

sub getSequencingCenterContactId {
    my($self) = @_;
  return $self->get("sequencing_center_contact_id");
}

sub setModificationDate {
  my($self,$value) = @_;
  $self->set("modification_date",$value);
}

sub getModificationDate {
    my($self) = @_;
  return $self->get("modification_date");
}

sub setUserRead {
  my($self,$value) = @_;
  $self->set("user_read",$value);
}

sub getUserRead {
    my($self) = @_;
  return $self->get("user_read");
}

sub setUserWrite {
  my($self,$value) = @_;
  $self->set("user_write",$value);
}

sub getUserWrite {
    my($self) = @_;
  return $self->get("user_write");
}

sub setGroupRead {
  my($self,$value) = @_;
  $self->set("group_read",$value);
}

sub getGroupRead {
    my($self) = @_;
  return $self->get("group_read");
}

sub setGroupWrite {
  my($self,$value) = @_;
  $self->set("group_write",$value);
}

sub getGroupWrite {
    my($self) = @_;
  return $self->get("group_write");
}

sub setOtherRead {
  my($self,$value) = @_;
  $self->set("other_read",$value);
}

sub getOtherRead {
    my($self) = @_;
  return $self->get("other_read");
}

sub setOtherWrite {
  my($self,$value) = @_;
  $self->set("other_write",$value);
}

sub getOtherWrite {
    my($self) = @_;
  return $self->get("other_write");
}

sub setRowUserId {
  my($self,$value) = @_;
  $self->set("row_user_id",$value);
}

sub getRowUserId {
    my($self) = @_;
  return $self->get("row_user_id");
}

sub setRowGroupId {
  my($self,$value) = @_;
  $self->set("row_group_id",$value);
}

sub getRowGroupId {
    my($self) = @_;
  return $self->get("row_group_id");
}

sub setRowProjectId {
  my($self,$value) = @_;
  $self->set("row_project_id",$value);
}

sub getRowProjectId {
    my($self) = @_;
  return $self->get("row_project_id");
}

sub setRowAlgInvocationId {
  my($self,$value) = @_;
  $self->set("row_alg_invocation_id",$value);
}

sub getRowAlgInvocationId {
    my($self) = @_;
  return $self->get("row_alg_invocation_id");
}

1;
