package GUS::Model::DoTS::RNAFeature_Row;

# THIS CLASS HAS BEEN AUTOMATICALLY GENERATED BY THE GUS::ObjRelP::Generator 
# PACKAGE.
#
# DO NOT EDIT!!

use strict;
use GUS::Model::DoTS::NAFeature;

use vars qw (@ISA);
@ISA = qw (GUS::Model::DoTS::NAFeature);

sub setDefaultParams {
  my ($self) = @_;
  $self->setVersionable(1);
  $self->setUpdateable(1);
}

sub setNumberOfExons {
  my($self,$value) = @_;
  $self->set("number_of_exons",$value);
}

sub getNumberOfExons {
    my($self) = @_;
  return $self->get("number_of_exons");
}

sub setTranslationStart {
  my($self,$value) = @_;
  $self->set("translation_start",$value);
}

sub getTranslationStart {
    my($self) = @_;
  return $self->get("translation_start");
}

sub setTranslationStop {
  my($self,$value) = @_;
  $self->set("translation_stop",$value);
}

sub getTranslationStop {
    my($self) = @_;
  return $self->get("translation_stop");
}

1;
