package GUS::Model::DoTS::AAFeature_Row;

# THIS CLASS HAS BEEN AUTOMATICALLY GENERATED BY THE GUS::ObjRelP::Generator 
# PACKAGE.
#
# DO NOT EDIT!!

use strict;
use GUS::Model::GusRow;

use vars qw (@ISA);
@ISA = qw (GUS::Model::GusRow);

sub setDefaultParams {
  my ($self) = @_;
  $self->setVersionable(1);
  $self->setUpdateable(1);
}

sub setAaFeatureId {
  my($self,$value) = @_;
  $self->set("aa_feature_id",$value);
}

sub getAaFeatureId {
    my($self) = @_;
  return $self->get("aa_feature_id");
}

sub setAaSequenceId {
  my($self,$value) = @_;
  $self->set("aa_sequence_id",$value);
}

sub getAaSequenceId {
    my($self) = @_;
  return $self->get("aa_sequence_id");
}

sub setFeatureNameId {
  my($self,$value) = @_;
  $self->set("feature_name_id",$value);
}

sub getFeatureNameId {
    my($self) = @_;
  return $self->get("feature_name_id");
}

sub setNaFeatureId {
  my($self,$value) = @_;
  $self->set("na_feature_id",$value);
}

sub getNaFeatureId {
    my($self) = @_;
  return $self->get("na_feature_id");
}

sub setSubclassView {
  my($self,$value) = @_;
  $self->set("subclass_view",$value);
}

sub getSubclassView {
    my($self) = @_;
  return $self->get("subclass_view");
}

sub setSequenceOntologyId {
  my($self,$value) = @_;
  $self->set("sequence_ontology_id",$value);
}

sub getSequenceOntologyId {
    my($self) = @_;
  return $self->get("sequence_ontology_id");
}

sub setDescription {
  my($self,$value) = @_;
  $self->set("description",$value);
}

sub getDescription {
    my($self) = @_;
  return $self->get("description");
}

sub setPfamEntryId {
  my($self,$value) = @_;
  $self->set("pfam_entry_id",$value);
}

sub getPfamEntryId {
    my($self) = @_;
  return $self->get("pfam_entry_id");
}

sub setMotifAaSequenceId {
  my($self,$value) = @_;
  $self->set("motif_aa_sequence_id",$value);
}

sub getMotifAaSequenceId {
    my($self) = @_;
  return $self->get("motif_aa_sequence_id");
}

sub setRepeatTypeId {
  my($self,$value) = @_;
  $self->set("repeat_type_id",$value);
}

sub getRepeatTypeId {
    my($self) = @_;
  return $self->get("repeat_type_id");
}

sub setExternalDatabaseReleaseId {
  my($self,$value) = @_;
  $self->set("external_database_release_id",$value);
}

sub getExternalDatabaseReleaseId {
    my($self) = @_;
  return $self->get("external_database_release_id");
}

sub setSourceId {
  my($self,$value) = @_;
  $self->set("source_id",$value);
}

sub getSourceId {
    my($self) = @_;
  return $self->get("source_id");
}

sub setPredictionAlgorithmId {
  my($self,$value) = @_;
  $self->set("prediction_algorithm_id",$value);
}

sub getPredictionAlgorithmId {
    my($self) = @_;
  return $self->get("prediction_algorithm_id");
}

sub setIsPredicted {
  my($self,$value) = @_;
  $self->set("is_predicted",$value);
}

sub getIsPredicted {
    my($self) = @_;
  return $self->get("is_predicted");
}

sub setReviewStatusId {
  my($self,$value) = @_;
  $self->set("review_status_id",$value);
}

sub getReviewStatusId {
    my($self) = @_;
  return $self->get("review_status_id");
}

sub setModificationDate {
  my($self,$value) = @_;
  $self->set("modification_date",$value);
}

sub getModificationDate {
    my($self) = @_;
  return $self->get("modification_date");
}

sub setUserRead {
  my($self,$value) = @_;
  $self->set("user_read",$value);
}

sub getUserRead {
    my($self) = @_;
  return $self->get("user_read");
}

sub setUserWrite {
  my($self,$value) = @_;
  $self->set("user_write",$value);
}

sub getUserWrite {
    my($self) = @_;
  return $self->get("user_write");
}

sub setGroupRead {
  my($self,$value) = @_;
  $self->set("group_read",$value);
}

sub getGroupRead {
    my($self) = @_;
  return $self->get("group_read");
}

sub setGroupWrite {
  my($self,$value) = @_;
  $self->set("group_write",$value);
}

sub getGroupWrite {
    my($self) = @_;
  return $self->get("group_write");
}

sub setOtherRead {
  my($self,$value) = @_;
  $self->set("other_read",$value);
}

sub getOtherRead {
    my($self) = @_;
  return $self->get("other_read");
}

sub setOtherWrite {
  my($self,$value) = @_;
  $self->set("other_write",$value);
}

sub getOtherWrite {
    my($self) = @_;
  return $self->get("other_write");
}

sub setRowUserId {
  my($self,$value) = @_;
  $self->set("row_user_id",$value);
}

sub getRowUserId {
    my($self) = @_;
  return $self->get("row_user_id");
}

sub setRowGroupId {
  my($self,$value) = @_;
  $self->set("row_group_id",$value);
}

sub getRowGroupId {
    my($self) = @_;
  return $self->get("row_group_id");
}

sub setRowProjectId {
  my($self,$value) = @_;
  $self->set("row_project_id",$value);
}

sub getRowProjectId {
    my($self) = @_;
  return $self->get("row_project_id");
}

sub setRowAlgInvocationId {
  my($self,$value) = @_;
  $self->set("row_alg_invocation_id",$value);
}

sub getRowAlgInvocationId {
    my($self) = @_;
  return $self->get("row_alg_invocation_id");
}

1;
