package GUS::Model::DoTS::Similarity_Table;

# THIS CLASS HAS BEEN AUTOMATICALLY GENERATED BY THE GUS::ObjRelP::Generator 
# PACKAGE.
#
# DO NOT EDIT!!


use strict;
use GUS::ObjRelP::DbiTable;
use vars qw (@ISA);
@ISA = qw (GUS::ObjRelP::DbiTable);

sub setDefaultParams {
  my $self = shift;
  $self->setChildList(
      ['GUS::Model::DoTS::ConsistentAlignment','similarity_id','similarity_id'],
      ['GUS::Model::DoTS::SimilaritySpan','similarity_id','similarity_id'],
      ['GUS::Model::DoTS::GeneFeatureSeqOverlap','similarity_id','similarity_id']);

  $self->setParentList(
      ['GUS::Model::Core::TableInfo','query_table_id','table_id'],
      ['GUS::Model::Core::TableInfo','subject_table_id','table_id'],
      ['GUS::Model::Core::AlgorithmInvocation','row_alg_invocation_id','algorithm_invocation_id'],
      ['GUS::Model::Core::GroupInfo','row_group_id','group_id'],
      ['GUS::Model::Core::UserInfo','row_user_id','user_id'],
      ['GUS::Model::Core::ProjectInfo','row_project_id','project_id']);

  $self->setAttributeNames(
      'similarity_id',
      'subject_table_id',
      'subject_id',
      'query_table_id',
      'query_id',
      'score',
      'bit_score_summary',
      'pvalue_mant',
      'pvalue_exp',
      'min_subject_start',
      'max_subject_end',
      'min_query_start',
      'max_query_end',
      'number_of_matches',
      'total_match_length',
      'number_identical',
      'number_positive',
      'is_reversed',
      'reading_frame',
      'modification_date',
      'user_read',
      'user_write',
      'group_read',
      'group_write',
      'other_read',
      'other_write',
      'row_user_id',
      'row_group_id',
      'row_project_id',
      'row_alg_invocation_id');

  $self->setQuotedAtts(
      'modification_date');

  $self->setAttInfo(
      {'col' => 'similarity_id', 'type' => 'NUMBER', 'prec' => 10, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'subject_table_id', 'type' => 'NUMBER', 'prec' => 5, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'subject_id', 'type' => 'NUMBER', 'prec' => 10, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'query_table_id', 'type' => 'NUMBER', 'prec' => 5, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'query_id', 'type' => 'NUMBER', 'prec' => 10, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'score', 'type' => 'FLOAT', 'prec' => 126, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'bit_score_summary', 'type' => 'FLOAT', 'prec' => 126, 'length' => 22, 'Nulls' => 1, 'base_type' => 'not set'}, 
      {'col' => 'pvalue_mant', 'type' => 'FLOAT', 'prec' => 126, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'pvalue_exp', 'type' => 'NUMBER', 'prec' => 6, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'min_subject_start', 'type' => 'NUMBER', 'prec' => 12, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'max_subject_end', 'type' => 'NUMBER', 'prec' => 12, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'min_query_start', 'type' => 'NUMBER', 'prec' => 12, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'max_query_end', 'type' => 'NUMBER', 'prec' => 12, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'number_of_matches', 'type' => 'NUMBER', 'prec' => 5, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'total_match_length', 'type' => 'NUMBER', 'prec' => 12, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'number_identical', 'type' => 'NUMBER', 'prec' => 12, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'number_positive', 'type' => 'NUMBER', 'prec' => 12, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'is_reversed', 'type' => 'NUMBER', 'prec' => 1, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'reading_frame', 'type' => 'NUMBER', 'prec' => 3, 'length' => 22, 'Nulls' => 1, 'base_type' => 'not set'}, 
      {'col' => 'modification_date', 'type' => 'DATE', 'prec' => '', 'length' => 7, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'user_read', 'type' => 'NUMBER', 'prec' => 1, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'user_write', 'type' => 'NUMBER', 'prec' => 1, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'group_read', 'type' => 'NUMBER', 'prec' => 1, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'group_write', 'type' => 'NUMBER', 'prec' => 1, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'other_read', 'type' => 'NUMBER', 'prec' => 1, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'other_write', 'type' => 'NUMBER', 'prec' => 1, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'row_user_id', 'type' => 'NUMBER', 'prec' => 12, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'row_group_id', 'type' => 'NUMBER', 'prec' => 4, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'row_project_id', 'type' => 'NUMBER', 'prec' => 4, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'}, 
      {'col' => 'row_alg_invocation_id', 'type' => 'NUMBER', 'prec' => 12, 'length' => 22, 'Nulls' => 0, 'base_type' => 'not set'});

  $self->setRealTableName('GUS::Model::DoTS::Similarity');

  $self->setIsView(0);

  $self->setParentRelations(
      ['GUS::Model::Core::TableInfo','query_table_id','table_id'], 
      ['GUS::Model::Core::TableInfo','subject_table_id','table_id'], 
      ['GUS::Model::Core::AlgorithmInvocation','row_alg_invocation_id','algorithm_invocation_id'], 
      ['GUS::Model::Core::GroupInfo','row_group_id','group_id'], 
      ['GUS::Model::Core::UserInfo','row_user_id','user_id'], 
      ['GUS::Model::Core::ProjectInfo','row_project_id','project_id']);

  $self->setChildRelations(
      ['GUS::Model::DoTS::ConsistentAlignment','similarity_id','similarity_id'], 
      ['GUS::Model::DoTS::SimilaritySpan','similarity_id','similarity_id'], 
      ['GUS::Model::DoTS::GeneFeatureSeqOverlap','similarity_id','similarity_id']);

  $self->setHasSequence(0);

  $self->setPrimaryKeyList('similarity_id');

  $self->setTableId(469);

}

1;

