<head>
    <title><?= $_SERVER['HTTP_HOST'] ?> /dashboard</title>
    <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />

    <link rel="stylesheet" type="text/css" href="css/main.css" />
    <link rel="stylesheet" type="text/css" href="css/ui-lightness/jquery-ui-1.8.21.custom.css" />
    <script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'></script>
    <script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js'></script>
    <script type='text/javascript' src='js/overlib.js'></script>
    <script type='text/javascript' src='js/main.js'></script>

    <script type="text/javascript">
      var ol_textcolor = "#003366";
      var ol_fgcolor = "#ffffff";
      var ol_bgcolor = "#003366";
      var ol_texsize = "11px";
      var ol_cellpad = "5";
      var ol_height = -1;
      var ol_vpos = ABOVE;
    </script>
</head>
